### PR TITLE
Add support for IgnorePaths

### PR DESCRIPTION
**Pull request by frenchfrywpepper**
Trigger a step if and only if at least one changed file matches the Path and also is not in IgnorePaths.

### CODE REVIEW

**Comment by ivotron** [comment]
rather than merging this, we could consider opening this PR against the official repo, as this is a feature that has been requested there (see https://github.com/buildkite-plugins/monorepo-diff-buildkite-plugin/issues/20). we could then transition to use that instead of having this fork

**Comment by ivotron** [comment]
afaik, the feature we needed that prompted the fork is already available in the offical repo, but i'm not 100%

**Comment by frenchfrywpepper** [comment]
The official repo has been abandoned

**Comment by frenchfrywpepper** [comment]
I see, it moved to https://github.com/buildkite-plugins/monorepo-diff-buildkite-plugin but I don't see the feature I want there.

**Comment by frenchfrywpepper** [comment]
Filed https://redpandadata.atlassian.net/browse/PESDLC-2076 for your consideration about moving off this fork.

**Review by simon0191 — APPROVED** [review]

**Pull request merged**
